-- ══════════════════════════════════════════════════════════════
-- V6__seed_all_loco_sheds.sql
-- Insert all missing loco sheds with ON CONFLICT (name) DO NOTHING
-- ══════════════════════════════════════════════════════════════

INSERT INTO loco_sheds (name, location, zone) VALUES
('Abu Road Diesel Loco Shed', 'Abu Road', 'NWR'),
('X~Agra', 'Agra City', 'NCR'),
('Arakkonam Electric Loco Shed', 'Arakkonam', 'SR'),
('Lucknow Diesel Loco Shed', 'Lucknow', 'NR'),
('Angul Electric Loco Shed', 'Angul', 'ECoR'),
('Ajni Electric Loco Shed', 'Ajni', 'CR'),
('Asansol Electric Loco Shed', 'Asansol', 'ER'),
('Bandra Diesel Loco Shed', 'Mumbai', 'WR'),
('Bhagat Ki Kothi Diesel Loco Shed', 'Jodhpur', 'NWR'),
('Bhilai Electric Loco Shed', 'Bhilai', 'SECR'),
('Barauni Electric Loco Shed', 'Barauni', 'ECR'),
('Bokaro Steel City Electric Loco Shed', 'Bokaro Steel City', 'SER'),
('Valsad Electric Loco Shed', 'Valsad', 'WR'),
('X~Bangalore Cantonment', 'Bangalore', 'SWR'),
('Bandel Electric Loco Shed', 'Bandel', 'ER'),
('Bondamunda Diesel Loco Shed', 'Bondamunda', 'SER'),
('X~Baripada', 'Baripada', 'SER'),
('X~Bangladesh Railway', 'Bangladesh', NULL),
('Vadodara Electric Loco Shed', 'Vadodara', 'WR'),
('Bhusaval Electric Loco Shed', 'Bhusaval', 'CR'),
('Bilaspur Electric Loco Shed', 'Bilaspur', 'SECR'),
('Barddhaman Diesel Loco Shed', 'Barddhaman', 'ER'),
('Vijayawada Diesel Loco Shed', 'Vijayawada', 'SCR'),
('Vijayawada Electric Loco Shed', 'Vijayawada', 'SCR'),
('X~CFC Cambodia', 'Cambodia', 'Chemin de fer du Cambodge'),
('X~Mozambique Ports and Railways', 'Mozambique, Africa', NULL),
('X~Chitpur Kolkata', 'Chitpur', 'ER'),
('Kurla Diesel Loco Shed', 'Kurla', 'CR'),
('Kanpur Electric Loco Shed', 'Kanpur', 'NCR'),
('Pt. Deen Dayal Upadhyaya Electric Loco Shed', 'Mughalsarai', 'ECR'),
('Pt. Deen Dayal Upadhyaya Diesel Loco Shed', 'Mughalsarai', 'ECR'),
('X~Dhaulpur', 'Dhaulpur', 'NCR'),
('Daund Electric Loco Shed', 'Daund', 'CR'),
('Erode Diesel Loco Shed', 'Erode', 'SR'),
('Erode Electric Loco Shed', 'Erode', 'SR'),
('Ernakulam Diesel Loco Shed', 'Ernakulam', 'SR'),
('Itarsi Diesel Loco Shed', 'Itarsi', 'WCR'),
('Itarsi Electric Loco Shed', 'Itarsi', 'WCR'),
('Phulera', 'Phulera', 'NWR'),
('Gonda Diesel Loco Shed', 'Gonda', 'NER'),
('Gandhidham Diesel Loco Shed (O/D)', 'Gandhidham', 'WR'),
('Gandhidham Diesel Loco Shed', 'Gandhidham', 'WR'),
('Gorakhpur Electric Loco Shed', 'Gorakhpur', 'NER'),
('Gomoh Electric Loco Shed', 'Gomoh', 'ER'),
('Golden Rock Diesel Loco Shed', 'Tiruchirapalli', 'SR'),
('Guntakal Diesel Loco Shed', 'Guntakal', 'SCR'),
('Guntakal Electric Loco Shed', 'Guntakal', 'SCR'),
('Gwalior', 'Gwalior', 'NCR'),
('Gooty Diesel Loco Shed', 'Gooty', 'SCR'),
('Ghaziabad Electric Loco Shed', 'Ghaziabad', 'NR'),
('Howrah Diesel Loco Shed', 'Howrah', 'ER'),
('Howrah Electric Loco Shed', 'Howrah', 'ER'),
('Ispat Nagar Electric Loco Shed', 'Ispat Nagar', 'SER'),
('Izzatnagar Diesel Loco Shed', 'Izzatnagar', 'NER'),
('Jhansi Diesel Loco Shed', 'Jhansi', 'NCR'),
('Jhansi Electric Loco Shed', 'Jhansi', 'NCR'),
('X~Jhanjharpur', 'Jhanjharpur', 'ECR'),
('Jamalpur Diesel Loco Shed', 'Jamalpur', 'ER'),
('Kharagpur Diesel Loco Shed', 'Kharagpur', 'SER'),
('Khanalampura Electric Loco Shed', 'Khanalampura', 'NR'),
('Krishnarajapuram Diesel Loco Shed', 'Bangalore', 'SWR'),
('Kalka', 'Kalka', 'NR'),
('X~KTM Malaysia', 'Keretapi Tanah Melayu, Malaysia', NULL),
('Katwa', 'Katwa', 'ER'),
('X~Kurduvadi', 'Kurduvadi', 'CR'),
('Kalyan Diesel Loco Shed', 'Kalyan', 'CR'),
('Kalyan Electric Loco Shed', 'Kalyan', 'CR'),
('Kazipet Diesel Loco Shed', 'Kazipet', 'SCR'),
('Kazipet Electric Loco Shed', 'Kazipet', 'SCR'),
('Ludhiana Diesel Loco Shed', 'Ludhiana', 'NR'),
('Ludhiana Electric Loco Shed', 'Ludhiana', 'NR'),
('Lallaguda Electric Loco Shed', 'Lallaguda', 'SCR'),
('X~Liluah', 'Howrah', 'ER'),
('X~Lumding', 'Lumding', 'NFR'),
('Mhow', 'Mhow', 'WR'),
('Motibagh Diesel Loco Shed', 'Nagpur', 'SECR'),
('Malda Town Electric Loco Shed', 'Malda Town', 'ER'),
('Moula Ali Diesel Loco Shed', 'Secunderabad', 'SCR'),
('X~Malian Ministry of Transport', 'Mali, West Africa', NULL),
('X~Myanmar Railways', 'Myanmar (Burma)', NULL),
('Mavli', 'Mavli', 'NWR'),
('X~Murtizapur', 'Murtizapur', 'CR'),
('Nagpur Electric Loco Shed', 'Nagpur', 'CR'),
('New Guwahati Diesel Loco Shed', 'Guwahati', 'NFR'),
('X~Unknown', NULL, NULL),
('X~Narkatiaganj Jn', 'Narkatiaganj', 'ECR'),
('New Katni Jn Diesel Loco Shed', 'Katni', 'WCR'),
('New Katni Jn Electric Loco Shed', 'Katni', 'WCR'),
('X~Nepal Railway Company Ltd.', 'Nepal', NULL),
('Neral', 'Neral', 'CR'),
('Pune Diesel Loco Shed', 'Pune', 'CR'),
('Pratapnagar', 'Vadodara', 'WR'),
('Pathankot', 'Pathankot', 'NR'),
('Patratu Diesel Loco Shed', 'Patratu', 'ECR'),
('Rourkela Electric Loco Shed', 'Rourkela', 'SER'),
('Roza Diesel Loco Shed', 'Roza', 'NR'),
('X~Rangapara North Jn', 'Rangapara', 'NFR'),
('Raipur Diesel Loco Shed', 'Raipur', 'SECR'),
('Royapuram Electric Loco Shed', 'Chennai', 'SR'),
('Ratlam Diesel Loco Shed', 'Ratlam', 'WR'),
('Sabarmati Diesel Loco Shed', 'Ahmedabad', 'WR'),
('Sealdah Diesel Loco Shed', 'Calcutta', 'ER'),
('Siliguri Diesel Loco Shed', 'Siliguri', 'NFR'),
('X~SNCS Senegal', 'Sénégal, Africa', 'Société nationale de chemins de fer du Sénégal'),
('Samastipur Diesel Loco Shed', 'Samastipur', 'ECR'),
('Santragachi Electric Loco Shed', 'Howrah', 'SER'),
('Saharanpur Electric Loco Shed', 'Saharanpur', 'NR'),
('X~Shakurbasti', 'Delhi', 'NR'),
('Saiyedpur Bhitri Electric Loco Shed', 'Saiyedpur Bhitri', 'NER'),
('Tatanagar Electric Loco Shed', 'Tatanagar', 'SER'),
('X~Tambaram', 'Chennai', 'SR'),
('X~Tindharia', 'Tindharia', 'NFR'),
('Tughlakabad Diesel Loco Shed', 'Tughlakabad', 'NR'),
('Tughlakabad Electric Loco Shed', 'Tughlakabad', 'NR'),
('Tondiarpet Diesel Loco Shed', 'Chennai', 'SR'),
('X~Togo Rail SA, West Africa', 'Togo Rail SA, West Africa', NULL),
('X~Ambala City', 'Ambala City', 'NR'),
('Hubli Diesel Loco Shed', 'Hubli', 'SWR'),
('Andal Diesel Loco Shed', 'Andal', 'ER'),
('Vatva Diesel Loco Shed', 'Vatva', 'WR'),
('Vishakapatnam Diesel Loco Shed', 'Vishakapatnam', 'ECoR'),
('Vishakapatnam Electric Loco Shed', 'Vishakapatnam', 'ECoR')
ON CONFLICT (name) DO NOTHING;
